import { GoogleGenerativeAI } from '@google/generative-ai';
import { TIMESTAMP_GENERATION_SYSTEM_PROMPT, TIMESTAMP_GENERATION_USER_PROMPT } from './prompts';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
// Note: Some regions/keys might require v1 specifically for Flash models
const modelConfig = { model: 'gemini-1.5-flash' };

export interface GeneratedTimestamp {
    time: string; // "00:00" or "00:00:00"
    title: string;
}

/**
 * Generate timestamps using Google Gemini from a raw transcript string.
 */
export async function generateTimestampsFromText(
    transcript: string,
    language: string = 'English'
): Promise<GeneratedTimestamp[]> {
    try {
        const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' }, { apiVersion: 'v1' });

        const fullPrompt = `${TIMESTAMP_GENERATION_SYSTEM_PROMPT}\n\n${TIMESTAMP_GENERATION_USER_PROMPT(transcript, language)}`;

        console.log('[GeminiAI] Generating timestamps from text...');
        const result = await model.generateContent(fullPrompt);
        const response = await result.response;
        const resultText = response.text();

        // Extract JSON from response
        const jsonMatch = resultText.match(/\[[\s\S]*\]/);
        if (!jsonMatch) {
            throw new Error('No JSON array found in Gemini response.');
        }

        const timestamps: GeneratedTimestamp[] = JSON.parse(jsonMatch[0]);

        if (timestamps.length === 0) {
            throw new Error('No timestamps generated by AI.');
        }

        // Ensure first timestamp is 00:00
        if (timestamps[0].time !== '00:00' && timestamps[0].time !== '0:00') {
            timestamps[0].time = '00:00';
        }

        return timestamps;
    } catch (error: any) {
        console.error('[GeminiAI] Error generating timestamps:', error);
        throw new Error(`Failed to generate timestamps: ${error.message}`);
    }
}
